### PR TITLE
Allow string names for ROIs

### PR DESCRIPTION
**Pull request by natmurad**
update readLabWorksheet to use read.csv because read.table does not read rois names column properly

includes index in bookendStr

remove as.numeric from annots and parseOverlayAttrs where it is not needed

### CODE REVIEW

**Comment by maddygriz** [comment]
Hi @natmurad,

Thanks for the updates. We have actually fixed both of these issues for the next Bioconductor release. These are fixed in the [`dev` branch](https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/tree/dev) if you want to use/test this branch. There are other updates to this branch seen in the [NEWS file](https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/dev/NEWS). This branch has gone through our code review process but has not been through V&V yet.  

Hope this helps and thanks again for your contribution. I'm closing this PR since we have already fixed the issues. 

Maddy

**Comment by maddygriz** [comment]
It looks like it ran without erroring but that of course doesn't always mean that it completely worked. 13 ROIs were removed but how many did you start with?

**Comment by natmurad** [comment]
This is the output from this new dev version.
It did not match the string ROIs that are those 13. I guess it is accepting or all names as strings, or all names as numeric because of some if you included, maybe? I do not know. I did not check this new code.

My corrections do not give this kind of warning because it recognizes any type of ROI names. It was the way that it worked with my dataset.

**Comment by maddygriz** [comment]
Do your ROI names potentially have either "\" or "=" characters in them? That is the only meaningful difference I see in our changes.

**Comment by natmurad** [comment]
Yes. 001#2 001#3a.
It was not chosen by me.

**Comment by maddygriz** [comment]
Cool I see the issue on my end. I will have a new branch up with bug fix in the next day or so. Thanks for working with me to try and fix this.

**Comment by maddygriz** [comment]
I have a fix in, not reviewed, in the `specialCharacterROIs` branch.

**Comment by natmurad** [comment]
Thank you!

**Pull request closed without merging**
