### PR TITLE
Solve minor issues

### PR DESCRIPTION
**Pull request by lardenoije**
Using this package I encountered some errors, likely because our data did not have numeric ROI labels and the lab worksheet was an Excel file. The proposed changes resolved all errors for our data.

### CODE REVIEW

**Comment by maddygriz** [comment]
Hi Roy,

Thanks for your contribution! I have a question before I review this proposed change. 

Where did your lab worksheet come from? Was it an excel file straight from the instrument or did it get converted by someone after downloading it? Or did it come from the DSPDA output? The numeric ROI labels are important for matching the annotations to the xml file so I just want to make sure I understand where all of your input files are coming from. 

Maddy

**Comment by lardenoije** [comment]
Hi Maddy,

The original lab worksheet was a .txt file, which I was told was exported from the DSP instrument, although I am currently not entirely sure if it does not come from DSPDA. That .txt file did contain Experiment Summary and Library Prep Summary header information besides the annotations, if that helps determining its exact origin. The "roi" column in the original file I received looked somewhat strange: "=""character-label""", so I changed it to "character-label" and converted the lab worksheet to .xlsx. The reason for this conversion is that I also use GeomxTools to process the data and the `readNanoStringGeoMxSet` function of that package expects the lab worksheet to be an excel data file.
I hope this clears things up.

Cheers, Roy

**Comment by maddygriz** [comment]
Hi Roy,

This package is expecting the original labworksheet.txt with that strange label: "=""character-label"". It looks like your changes, while helping your xlsx file and honestly being more intuitive, cause problems for the original files so I can't merge them in. I will work on having the same input file from GeomxTools work in this package, thanks for bringing that to my attention. 

For your next study, I would suggest either reverting back to the original code and using the labworksheet.txt or continuing using your updated code with an xlsx made the same way again. If you mix the input file and code, you will get errors. 

Thank you again for your contribution and don't hesitate to reach out again if you find an issue or want something added to the package.
Maddy

**Comment by lardenoije** [comment]
Hi Maddy,

I understand. Having consistent inputs across this package and GeomxTools would indeed be useful!

Cheers, Roy

**Comment by maddygriz** [comment]
Hi Roy,

We have added this as an issue in both packages to have consistent inputs! Thanks again for drawing our attention to this issue. 

Maddy

**Pull request closed without merging**
