### PR TITLE
reduce test data size

### PR DESCRIPTION
**Pull request by maddygriz**
reduce kidney.zip test data size and update tests around it
tar file is now 4.5 MB and below the 5 MB requirement

```
> devtools::test("~/SpatialOmicsOverlay/")
ℹ Testing SpatialOmicsOverlay
══ Results ═════════════════════════════════════════════════════════════
Duration: 123.2 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 422 ]
```

```
> devtools::test_active_file(file = "~/SpatialOmicsOverlay/longtests/testthat/test_coordinateGeneration.R")
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 31 ]
```

### CODE REVIEW

**Comment by maddygriz** [comment]
Lower retina reduces vignette size but keeps the image looking clean. Might affect Apple users for [blurrier images](http://zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/#the-fig.retina-argument-is-a-resolution-multiplier).

**Comment by eveilyeverafter** [comment]
I do not see any differences in blurriness when I toggle between my retina display and my external (non-retina) monitor.

**Comment by mgrout81** [comment]
Task: 
In the terminal, run R CMD build path/to/SpatialOmicsOverlay/, this will create a tar file and see if that file is <5MB in size.

Result: 
File was 4.4M.

**Comment by mgrout81** [comment]
Task: Run two test commands.
```
devtools::test("~/data/mgrout/soo_v1.1_testing/pr_52/SpatialOmicsOverlay/")
# ══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════════
# Duration: 126.6 s
# 
# [ FAIL 0 | WARN 0 | SKIP 0 | PASS 422 ]

devtools::test_active_file(file = "~/data/mgrout/soo_v1.1_testing/pr_52/SpatialOmicsOverlay/longtests/testthat/test_coordinateGeneration.R")
# |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=19s  
# |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=20s  
# [ FAIL 0 | WARN 0 | SKIP 0 | PASS 31 ]
```

Result: No problems

**Comment by mgrout81** [comment]
Task: evaluate images in the vignette.

Result: I opened the vignette Rmd and knitted it with the RStudio knit button. I opened up the resulting HTML and looked at it side by side with the Bioconductor vignette HTML. The image resolutions looked the same to me.

**Comment by mgrout81** [comment]
Task: run R CMD check path/to/SpatialOmicsOverlay.tar.gz this will run all of the package building tests: knitting vignettes, running tests, running examples, checking documentation, etc. 

Result: finished with 1 warning, 1 error, and 4 notes. The error and warning pertain to generating PDFs and Maddy has confirmed this is expected output. See 00check.log contents below.

```
* using log directory ‘/home/rstudio/data/mgrout/soo_v1.1_testing/pr_52/SpatialOmicsOverlay.Rcheck’
* using R version 4.3.1 (2023-06-16)
* using platform: x86_64-pc-linux-gnu (64-bit)
* R was compiled by
    gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
    GNU Fortran (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
* running under: Ubuntu 22.04.2 LTS
* using session charset: UTF-8
* checking for file ‘SpatialOmicsOverlay/DESCRIPTION’ ... OK
* this is package ‘SpatialOmicsOverlay’ version ‘1.1.1’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘SpatialOmicsOverlay’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is  5.5Mb
  sub-directories of 1Mb or more:
    doc       2.0Mb
    extdata   3.0Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... NOTE
License components which are templates and need '+ file LICENSE':
  MIT
* checking top-level files ... NOTE
File
  LICENSE
is not mentioned in the DESCRIPTION file.
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
plotSpatialOverlay: no visible binding for global variable ‘xcoor’
plotSpatialOverlay: no visible binding for global variable ‘ycoor’
plotSpatialOverlay: no visible binding for global variable ‘sampleID’
plotSpatialOverlay: no visible binding for global variable ‘Target’
scaleBarPrinting: no visible binding for global variable ‘X’
scaleBarPrinting: no visible binding for global variable ‘Y’
Undefined global functions or variables:
  Target X Y sampleID xcoor ycoor
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... OK
  Running ‘testthat.R’
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ... NONE
  ‘SpatialOmicsOverlay.Rmd’ using ‘UTF-8’... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without index ... ERROR
Re-running with no redirection of stdout/stderr.
* DONE
Status: 1 ERROR, 1 WARNING, 4 NOTEs

```

**Review by mgrout81 — APPROVED** [review]

**Pull request merged**
